In [1]:
import math
import torch
from torch import nn 
from d2l import torch as d2l

d:\programfiles\Anaconda\anaconda\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] 找不到指定的程序。'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [2]:
def masked_softmax(X, valid_lens):
    # X:3D张量，valid_lens:1D or 2D张量
    if valid_lens is None:
        return nn.functional.softmax(X, dim=-1)
    else:
        shape = X.shape
        if valid_lens.dim() == 1:  # valid_lens: 1D
            valid_lens = torch.repeat_interleave(valid_lens, shape[1])
        else: # valid_lens :2D
            valid_lens = valid_lens.reshape(-1)
        X = d2l.sequence_mask(X.reshape(-1, shape[-1]), valid_lens, value=-1e6)
        return nn.functional.softmax(X.reshape(shape), dim=-1)
            

In [3]:
import torch

# 假设 batch_size=2, sequence_length=4, feature_dim=3
batch_size = 2
sequence_length = 4
feature_dim = 3

# 创建一个示例的三维张量 X
X = torch.randn((batch_size, sequence_length, feature_dim))

# 假设 valid_lens 是一个一维张量，每个元素表示对应序列的有效长度
valid_lens = torch.tensor([3, 2])

# 将 valid_lens 中的每个元素重复 sequence_length 次
expanded_valid_lens = torch.repeat_interleave(valid_lens, sequence_length)

# 输出结果
print("原始 valid_lens:", valid_lens)
print("重复后的 valid_lens:", expanded_valid_lens)


原始 valid_lens: tensor([3, 2])
重复后的 valid_lens: tensor([3, 3, 3, 3, 2, 2, 2, 2])


In [4]:
print(masked_softmax(X, valid_lens))

tensor([[[0.5181, 0.2561, 0.2258],
         [0.2285, 0.6253, 0.1461],
         [0.6250, 0.3415, 0.0336],
         [0.5456, 0.1670, 0.2874]],

        [[0.4227, 0.5773, 0.0000],
         [0.4146, 0.5854, 0.0000],
         [0.2607, 0.7393, 0.0000],
         [0.1716, 0.8284, 0.0000]]])


In [6]:
X.reshape(-1, X.shape[-1])

tensor([[-5.8062e-03, -7.1049e-01, -8.3661e-01],
        [-1.3666e-01,  8.7001e-01, -5.8375e-01],
        [ 9.0399e-01,  2.9955e-01, -2.0204e+00],
        [ 7.8624e-01, -3.9792e-01,  1.4515e-01],
        [ 1.7435e-01,  4.8610e-01, -1.0000e+06],
        [-7.4360e-02,  2.7063e-01, -1.0000e+06],
        [-3.6183e-01,  6.8051e-01, -1.0000e+06],
        [-9.7340e-01,  6.0073e-01, -1.0000e+06]])

In [7]:
X

tensor([[[-5.8062e-03, -7.1049e-01, -8.3661e-01],
         [-1.3666e-01,  8.7001e-01, -5.8375e-01],
         [ 9.0399e-01,  2.9955e-01, -2.0204e+00],
         [ 7.8624e-01, -3.9792e-01,  1.4515e-01]],

        [[ 1.7435e-01,  4.8610e-01, -1.0000e+06],
         [-7.4360e-02,  2.7063e-01, -1.0000e+06],
         [-3.6183e-01,  6.8051e-01, -1.0000e+06],
         [-9.7340e-01,  6.0073e-01, -1.0000e+06]]])